exports.DEFAULT_GOOGLE_SEARCH_DOMAIN_COUNTRY_CODE = 'US';

exports.GOOGLE_SEARCH_URL_REGEX = new RegExp(`^(http|https)://(www.){0,1}((${exports.GOOGLE_SEARCH_DOMAINS.join(')|(')}))/search?.*$`, 'i');

exports.DEFAULT_GOOGLE_SEARCH_DOMAIN_COUNTRY_CODE = 'US';

exports.REQUIRED_PROXY_GROUP = 'GOOGLE_SERP';

exports.GOOGLE_DEFAULT_RESULTS_PER_PAGE = 10;

/*
const {
    REQUIRED_PROXY_GROUP, GOOGLE_DEFAULT_RESULTS_PER_PAGE, DEFAULT_GOOGLE_SEARCH_DOMAIN_COUNTRY_CODE,
    GOOGLE_SEARCH_DOMAIN_TO_COUNTRY_CODE, GOOGLE_SEARCH_URL_REGEX } = require('./consts');
*/
